version: "3"
services:
  # first service, the database
  db:
    image: mongo:latest
    container_name: mongodb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGODB_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGODB_PASSWORD}
    volumes:
      - ./database:/data/db
    ports:
      - ${MONGODB_PORT}:27017
    restart: unless-stopped

  # an optional dbms to view the database besides app
  db_view:
    image: mongo-express
    container_name: mongo-express
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_SERVER=${MONGODB_HOST}
      - ME_CONFIG_MONGODB_ADMINUSERNAME=${MONGODB_USER}
      - ME_CONFIG_MONGODB_ADMINPASSWORD=${MONGODB_PASSWORD}
    depends_on:
      - "to_db"
    restart: on-failure

  # app to insert to mongodb
  to_db:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: weather-pull
    env_file:
      - .env
    depends_on:
      - "db"
