version: "3"
services:
  db:
    image: mongo:latest
    container_name: mongodb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=DockerWeather1
    volumes:
      - ./database:/data/db
    ports:
      - 27017:27017
    restart: unless-stopped
