version: "3"
services:
  # first service, the database
  db:
    image: mongo:latest
    container_name: mongodb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGODB_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGODB_PASSWORD}
    volumes:
      - ./database:/data/db
    ports:
      - ${MONGODB_PORT}:27017
    restart: unless-stopped

  # app to insert to mongodb
  to_db:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: weather-pull
    env_file:
      - .env
    depends_on:
      - "db"
